/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package project;

import project.CodingChallenge.CircularArray;

public class App {

    public static void main(String[] args) {
        CircularArray<String> list = new CircularArray<>(3);

        list.add("First");
        list.add("Second");
        list.add("Third");

        for(String word : list){
            System.out.println(word);
        }
    }
}
